name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Compose
        run: sudo apt-get install docker-compose

      - name: Build and run containers
        run: |
          docker-compose up -d --build

      - name: Wait for the server to be ready
        run: |
          until curl -s http://127.0.0.1:5000 > /dev/null; do
            echo "Waiting for the server to be ready..."
            sleep 1
          done
          echo "Server is up and running!"

      - name: Run tests
        run: |
          curl http://127.0.0.1:5000  # Ubah perintah ini sesuai dengan tes Anda

      - name: Tear down
        run: docker-compose down
